version = 0.1

# ==============================================================
# 開発環境 (dev)
# ==============================================================
[dev.deploy.parameters]
stack_name          = "poker-tools-dev"
region              = "ap-northeast-1"
capabilities        = "CAPABILITY_NAMED_IAM"
confirm_changeset   = false
fail_on_empty_changeset = false
parameter_overrides = "Environment=dev"

# ==============================================================
# 本番環境 (prod)
# ==============================================================
[prod.deploy.parameters]
stack_name          = "poker-tools-prod"
region              = "ap-northeast-1"
capabilities        = "CAPABILITY_NAMED_IAM"
confirm_changeset   = true     # prod はチェンジセット内容を確認してから適用
fail_on_empty_changeset = false
parameter_overrides = "Environment=prod"
